### ISSUE TITLE
Peer to peer code reviews for Morning Session

### ISSUE THREAD

**Issue by nevisende** [kingqabil/Awesome-Books2#4]
I checked **your last PR**. There is nothing to say.You've done a great job. Congratulations :-)
If anyone in the group finds issues you can write in below.

Happy coding...

**Comment by cwaku** [comment]
> I checked **your last PR**. There is nothing to say.You've done a great job. Congratulations :-) If anyone in the group finds issues you can write in below.
> 
> Happy coding...

Thank you for your comment
